//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoEfectuado
    {
        public int Id { get; set; }
        public string NroTransaccion { get; set; }
        public string Ente { get; set; }
        public string NroCliente { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Cuota { get; set; }
        public string Referencia { get; set; }
        public string Concepto { get; set; }
        public string Path { get; set; }
        public Nullable<int> TipoComprobante { get; set; }
    }
}
